# Generated by Django 5.1.4 on 2025-06-23 22:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=11)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=7)),
                ('streetAddress', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=20)),
                ('region', models.CharField(max_length=20)),
                ('district', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('previousSchool', models.CharField(max_length=50)),
                ('gpa', models.FloatField()),
                ('programOfInterest', models.CharField(max_length=100)),
                ('sop', models.CharField(max_length=100)),
                ('emergencyName', models.CharField(max_length=50)),
                ('emergencyPhone', models.CharField(max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
